name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      NODE_ENV: production
      PORT: 5057
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      ORIGIN: ${{ vars.ORIGIN }}
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x" # Use a Node.js LTS version

      - name: Navigate to client directory
        run: cd client

      - name: Install dependencies
        run: npm ci
        working-directory: client

      - name: Install eslint-plugin-react
        run: npm install eslint-plugin-react
        working-directory: client

      - name: Install eslint-plugin-prettier
        run: npm install eslint-plugin-prettier
        working-directory: client

      - name: Debugging
        run: |
          ls -al node_modules/eslint-plugin-react
          cat client/.eslintrc.js
          ls -al node_modules/.
        working-directory: client

      - name: Build frontend
        run: |
          npm ci
          npm run lint
          npm run build
        working-directory: client

      - name: Upload frontend
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: client/build
          destination-github-username: "freight-capstone"
          destination-repository-name: "log1"
          user-email: algie0506@gmail.com
          commit-message: Production
          target-branch: log1-frontend

      - name: Build backend
        run: |
          cd server
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "PORT=5057" >> .env
          echo "NODE_ENV=production" >> .env
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
          echo "ORIGIN=${{ vars.ORIGIN }}" >> .env
          npm ci
          npm run lint
          rm -rf node_modules

      - name: Upload backend
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          NODE_ENV: production
          PORT: 5057
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          ORIGIN: ${{ vars.ORIGIN }}
        with:
          source-directory: server/
          destination-github-username: "freight-capstone"
          destination-repository-name: "log1"
          user-email: algie0506@gmail.com
          commit-message: Production
          target-branch: log1-backend
