name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    env:
      VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }} # Add this at job level

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build frontend
        env:
          VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }} # Add this at job level

        run: |
          cd client
          echo "VITE_APP_API_URL=${{secrets.VITE_APP_API_URL}}" >> .env

          npm i
          npm run lint
          npm run build

      - name: Upload frontend
        id: push_directory_frontend
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: client/build
          destination-github-username: "freight-capstone"
          # Replace with your module name
          destination-repository-name: "log1"
          # Replace with your email address
          user-email: algie0506@gmail.com
          # Replace (optional)
          commit-message: Production
          # Replace core1 with your module name
          target-branch: log1-frontend

      - name: Build backend
        # Change the following commands if you have custom build
        run: |
          cd server
          echo "NODE_ENV=${{vars.NODE_ENV}}" >> .env
          echo "ORIGIN=${{vars.ORIGIN}}" >> .env
          echo "PORT=${{vars.PORT}}" >> .env
          echo "MONGO_URI=${{secrets.MONGO_URI}}" >> .env
          echo "ACCESS_TOKEN_SECRET=${{secrets.ACCESS_TOKEN_SECRET}}" >> .env
          echo "REFRESH_TOKEN_SECRET=${{secrets.REFRESH_TOKEN_SECRET}}" >> .env
          echo "SESSION_SECRET=${{secrets.SESSION_SECRET}}" >> .env
          npm i
          npm run lint
          rm -rf node_modules

      - name: Upload backend
        id: push_directory_backend
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: server/
          destination-github-username: "freight-capstone"
          # Replace with your module name
          destination-repository-name: "log1"
          # Replace with your email address
          user-email: algie0506@gmail.com
          # Replace (optional)
          commit-message: Production
          # Replace core1 with your module name
          target-branch: log1-backend
